#!/bin/sh
#
# 把 UCI 里的调优设置落盘并立即生效。
#
# 为什么写 /etc/sysctl.d/ 而不是往 /etc/sysctl.conf 追加:
# OpenWrt 的 /etc/init.d/sysctl 按 "/etc/sysctl.d/*.conf /etc/sysctl.conf"
# 的顺序加载, sysctl.conf 排在最后、优先级最高。往它追加有两个问题 ——
# 反复执行会堆出重复行, 而且没有安全的改回方式。drop-in 文件由本包独占,
# 每次整份重写即可。
#
# 代价是 sysctl.conf 里若残留同名键, 它仍然会压过 drop-in。所以下面会把
# 本包管理的那几个键从 sysctl.conf 里摘掉(先备份), 否则界面显示的值和系统
# 实际生效的值会对不上。

set -u

CONFIG=tuning
DROPIN="${LFAPP_SYSCTL_DROPIN:-/etc/sysctl.d/99-liquid-formula.conf}"
SYSCTL_CONF="${LFAPP_SYSCTL_CONF:-/etc/sysctl.conf}"
BACKUP="${SYSCTL_CONF}.liquid-formula.bak"
SYSCTL_BIN="${LFAPP_SYSCTL_BIN:-sysctl}"
UCI_BIN="${LFAPP_UCI_BIN:-uci}"
GREP_BIN="${LFAPP_GREP_BIN:-grep}"
INIT_DIR="${LFAPP_INIT_DIR:-/etc/init.d}"
FLOCK_BIN="${LFAPP_FLOCK_BIN:-flock}"
LOCK_FILE="${LFAPP_TUNING_LOCK:-/var/lock/liquid-formula-tuning.lock}"
LOCK_WAIT="${LFAPP_TUNING_LOCK_WAIT:-30}"
OPENWRT_RELEASE_FILE="${LFAPP_OPENWRT_RELEASE:-/etc/openwrt_release}"
LOG_TAG=liquid-formula-tuning

MANAGED_RE='^[[:space:]]*(net\.ipv4\.tcp_fastopen|net\.core\.default_qdisc|net\.ipv4\.tcp_congestion_control|net\.ipv4\.tcp_max_syn_backlog)[[:space:]]*='

FAILED=''
DROPIN_NEW=''
SYSCTL_NEW=''
BACKUP_NEW=''
DROPIN_OLD=''
SYSCTL_OLD=''
BACKUP_OLD=''
HAD_DROPIN=0
HAD_BACKUP=0
DROPIN_CHANGED=0
SYSCTL_CHANGED=0
BACKUP_CHANGED=0
STRIP_NEEDED=0
RESTORE_NEEDED=0

cleanup_temps() {
	[ -z "$DROPIN_NEW" ] || rm -f "$DROPIN_NEW"
	[ -z "$SYSCTL_NEW" ] || rm -f "$SYSCTL_NEW"
	[ -z "$BACKUP_NEW" ] || rm -f "$BACKUP_NEW"
	[ -z "$DROPIN_OLD" ] || rm -f "$DROPIN_OLD"
	[ -z "$SYSCTL_OLD" ] || rm -f "$SYSCTL_OLD"
	[ -z "$BACKUP_OLD" ] || rm -f "$BACKUP_OLD"
}

trap cleanup_temps EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

log() {
	logger -t "$LOG_TAG" -- "$*" 2>/dev/null || true
}

fail() {
	printf 'apply-tuning: %s\n' "$*" >&2
}

# Apply、disable 和包卸载的 restore 会改同三份持久化状态，必须共用同一把
# 真正的锁。以子进程持锁覆盖整个脚本，避免两个事务各自正确却交错提交。
if [ "${LFAPP_TUNING_LOCKED:-0}" != 1 ]; then
	case "$LOCK_WAIT" in
		''|*[!0-9]*)
			fail "invalid tuning lock wait"
			exit 1
			;;
	esac
	mkdir -p "$(dirname "$LOCK_FILE")" || {
		fail "cannot create tuning lock directory"
		exit 1
	}
	LFAPP_TUNING_LOCKED=1
	export LFAPP_TUNING_LOCKED
	"$FLOCK_BIN" -w "$LOCK_WAIT" -E 75 "$LOCK_FILE" sh "$0" "$@"
	lock_rc=$?
	[ "$lock_rc" != 75 ] || fail "another tuning transaction is in progress"
	exit "$lock_rc"
fi

uci_get() {
	$UCI_BIN -q get "$CONFIG.main.$1" 2>/dev/null
}

# 这些值会原样进入 sysctl.conf 语法和 sysctl -w 的参数, 必须先约束形状。
valid_uint() {
	case "$1" in
		''|*[!0-9]*) return 1 ;;
	esac
	[ "${#1}" -le 10 ]
}

valid_name() {
	case "$1" in
		''|*[!a-z0-9_]*) return 1 ;;
	esac
	[ "${#1}" -le 32 ]
}

read_openwrt_release() {
	local line value
	[ -r "$OPENWRT_RELEASE_FILE" ] || return 1
	while IFS= read -r line; do
		case "$line" in
			DISTRIB_RELEASE=*)
				value=${line#DISTRIB_RELEASE=}
				case "$value" in
					\'*\') value=${value#\'}; value=${value%\'} ;;
					\"*\") value=${value#\"}; value=${value%\"} ;;
				esac
				printf '%s\n' "$value"
				return 0
				;;
		esac
	done < "$OPENWRT_RELEASE_FILE"
	return 1
}

supports_cake_mq() {
	local release major rest minor
	release="$(read_openwrt_release)" || return 1
	# Main-branch builds report a bare "SNAPSHOT" with no version numbers at
	# all. They always track something newer than the last tagged release, so
	# the numeric gate below must not reject them. Release-branch snapshots
	# keep their numeric prefix ("24.10-SNAPSHOT") and stay comparable.
	case "$release" in
		SNAPSHOT|snapshot) return 0 ;;
	esac
	release=${release%-SNAPSHOT}
	release=${release%-snapshot}
	case "$release" in
		*.*) ;;
		*) return 1 ;;
	esac
	major=${release%%.*}
	rest=${release#*.}
	minor=${rest%%.*}
	case "$major" in ''|*[!0-9]*) return 1 ;; esac
	case "$minor" in ''|*[!0-9]*) return 1 ;; esac
	[ "$major" -gt 25 ] || { [ "$major" -eq 25 ] && [ "$minor" -ge 12 ]; }
}

# 所有持久化文件都先在目标目录旁边准备好，再用 rename 提交。这样既不会
# 原地截断 sysctl.conf，也不会在 drop-in 尚未准备好时先摘走用户设置。
stage_dropin() {
	[ ! -L "$DROPIN" ] || {
		fail "$DROPIN is a symlink; refusing to replace it"
		return 1
	}
	mkdir -p "$(dirname "$DROPIN")" || {
		fail "cannot create $(dirname "$DROPIN")"
		return 1
	}

	umask 022
	DROPIN_NEW="$(mktemp "${DROPIN}.new.XXXXXX")" || {
		fail "cannot create a temporary file next to $DROPIN"
		return 1
	}
	if ! cat > "$DROPIN_NEW" <<EOF
# Generated by Liquid Formula. Edit the Tuning Utility page instead; this file
# is rewritten on every apply.
net.ipv4.tcp_fastopen = $tcp_fastopen
net.core.default_qdisc = $default_qdisc
net.ipv4.tcp_congestion_control = $congestion_control
net.ipv4.tcp_max_syn_backlog = $backlog
EOF
	then
		fail "cannot write $DROPIN"
		return 1
	fi
	chmod 0644 "$DROPIN_NEW" || {
		fail "cannot set permissions on the temporary drop-in"
		return 1
	}
}

# 准备摘除托管键后的 sysctl.conf 和同一时刻的备份；此函数不改正式文件。
stage_stripped_sysctl_conf() {
	local grep_rc

	[ -f "$SYSCTL_CONF" ] || return 0
	[ ! -L "$SYSCTL_CONF" ] || {
		fail "$SYSCTL_CONF is a symlink; refusing to edit it"
		return 1
	}

	"$GREP_BIN" -qE "$MANAGED_RE" "$SYSCTL_CONF" 2>/dev/null
	grep_rc=$?
	case "$grep_rc" in
		0) ;;
		1) return 0 ;;
		*)
			fail "cannot inspect $SYSCTL_CONF for managed keys"
			return 1
			;;
	esac

	BACKUP_NEW="$(mktemp "${BACKUP}.new.XXXXXX")" || return 1
	cp -p "$SYSCTL_CONF" "$BACKUP_NEW" || {
		fail "cannot back up $SYSCTL_CONF"
		return 1
	}

	SYSCTL_NEW="$(mktemp "${SYSCTL_CONF}.new.XXXXXX")" || return 1
	# 先复制再覆写临时文件是为了保留 sysctl.conf 原来的权限；正式路径只会
	# 被下面的原子 rename 替换，绝不通过重定向截断。
	cp -p "$SYSCTL_CONF" "$SYSCTL_NEW" || return 1

	# 顺带把手工脚本追加的整块注释也去掉, 只留下不相干的行。
	awk '
		/^[[:space:]]*#[[:space:]]*Custom Network Optimization[[:space:]]*$/ { next }
		/^[[:space:]]*net\.ipv4\.tcp_fastopen[[:space:]]*=/ { next }
		/^[[:space:]]*net\.core\.default_qdisc[[:space:]]*=/ { next }
		/^[[:space:]]*net\.ipv4\.tcp_congestion_control[[:space:]]*=/ { next }
		/^[[:space:]]*net\.ipv4\.tcp_max_syn_backlog[[:space:]]*=/ { next }
		{ print }
	' "$SYSCTL_CONF" > "$SYSCTL_NEW" || return 1

	STRIP_NEEDED=1
	return 0
}

# 准备恢复文件；仅在 drop-in 仍存在、即确实处于一次活跃管理周期时调用。
# 成功关闭后会删除备份，因此旧版本遗留但已无 drop-in 的备份不会复活用户
# 后来主动删除的设置。
stage_restored_sysctl_conf() {
	local missing grep_rc

	[ -f "$BACKUP" ] || return 0
	[ ! -L "$BACKUP" ] || {
		fail "$BACKUP is a symlink; refusing to restore from it"
		return 1
	}
	"$GREP_BIN" -qE "$MANAGED_RE" "$BACKUP" 2>/dev/null
	grep_rc=$?
	case "$grep_rc" in
		0) ;;
		1) return 0 ;;
		*)
			fail "cannot inspect $BACKUP for managed keys"
			return 1
			;;
	esac
	[ -f "$SYSCTL_CONF" ] || {
		fail "$SYSCTL_CONF is missing; refusing to remove the active drop-in"
		return 1
	}
	[ ! -L "$SYSCTL_CONF" ] || {
		fail "$SYSCTL_CONF is a symlink; refusing to remove the active drop-in"
		return 1
	}

	# 逐键判断。原先只要 sysctl.conf 里还剩任意一个托管键就整批跳过, 其余的键
	# 就永久缺失了。
	missing="$(awk '
		function managed(line) {
			return line ~ /^[[:space:]]*(net\.ipv4\.tcp_fastopen|net\.core\.default_qdisc|net\.ipv4\.tcp_congestion_control|net\.ipv4\.tcp_max_syn_backlog)[[:space:]]*=/
		}
		function key_of(line, key) {
			key = line
			sub(/[[:space:]]*=.*$/, "", key)
			gsub(/[[:space:]]/, "", key)
			return key
		}
		FNR == NR {
			if (managed($0)) {
				lines[++count] = $0
				keys[count] = key_of($0)
			}
			next
		}
		managed($0) { present[key_of($0)] = 1 }
		END {
			for (i = 1; i <= count; i++)
				if (!present[keys[i]])
					print lines[i]
		}
	' "$BACKUP" "$SYSCTL_CONF")" || {
		fail "cannot compare $BACKUP with $SYSCTL_CONF"
		return 1
	}
	[ -n "$missing" ] || return 0

	SYSCTL_NEW="$(mktemp "${SYSCTL_CONF}.new.XXXXXX")" || return 1
	cp -p "$SYSCTL_CONF" "$SYSCTL_NEW" || return 1
	{
		printf '\n# Restored by Liquid Formula when kernel tuning was turned off.\n'
		printf '%s\n' "$missing"
	} >> "$SYSCTL_NEW" || return 1
	RESTORE_NEEDED=1
}

# 保存正式文件的旧版本供失败回滚。快照也放在同一目录，以便恢复时用 rename。
snapshot_file() {
	local source="$1" snapshot
	snapshot="$(mktemp "${source}.rollback.XXXXXX")" || return 1
	cp -p "$source" "$snapshot" || {
		rm -f "$snapshot"
		return 1
	}
	printf '%s\n' "$snapshot"
}

restore_snapshot() {
	local destination="$1" snapshot="$2" existed="$3"
	if [ "$existed" = 1 ]; then
		mv -f "$snapshot" "$destination"
	else
		rm -f "$destination"
	fi
}

rollback_enable() {
	local failed=0
	if [ "$BACKUP_CHANGED" = 1 ]; then
		if restore_snapshot "$BACKUP" "$BACKUP_OLD" "$HAD_BACKUP"; then
			BACKUP_OLD=''
		else
			failed=1
		fi
	fi
	if [ "$DROPIN_CHANGED" = 1 ]; then
		if restore_snapshot "$DROPIN" "$DROPIN_OLD" "$HAD_DROPIN"; then
			DROPIN_OLD=''
		else
			failed=1
		fi
	fi
	[ "$failed" = 0 ]
}

commit_enable() {
	local invalidate_stale=0

	[ ! -L "$DROPIN" ] || {
		fail "$DROPIN became a symlink; refusing to replace it"
		return 1
	}
	[ ! -L "$BACKUP" ] || {
		fail "$BACKUP is a symlink; refusing to replace it"
		return 1
	}
	if [ -e "$DROPIN" ] || [ -L "$DROPIN" ]; then
		HAD_DROPIN=1
		DROPIN_OLD="$(snapshot_file "$DROPIN")" || return 1
	fi
	if [ -e "$BACKUP" ] || [ -L "$BACKUP" ]; then
		HAD_BACKUP=1
		BACKUP_OLD="$(snapshot_file "$BACKUP")" || return 1
	fi
	# 无托管键且此前没有活跃 drop-in，说明这个备份是旧管理周期遗留的。
	# 新周期不能继承它，否则关闭时会把用户已经删除的值重新加回来。
	[ "$STRIP_NEEDED" = 1 ] || [ "$HAD_DROPIN" = 1 ] || invalidate_stale=1

	mv -f "$DROPIN_NEW" "$DROPIN" || {
		fail "cannot install $DROPIN"
		return 1
	}
	DROPIN_NEW=''
	DROPIN_CHANGED=1

	if [ "$STRIP_NEEDED" = 1 ]; then
		mv -f "$BACKUP_NEW" "$BACKUP" || {
			fail "cannot install the $SYSCTL_CONF backup"
			rollback_enable || fail "cannot roll back the failed tuning transaction"
			return 1
		}
		BACKUP_NEW=''
		BACKUP_CHANGED=1

		mv -f "$SYSCTL_NEW" "$SYSCTL_CONF" || {
			fail "cannot atomically update $SYSCTL_CONF"
			rollback_enable || fail "cannot roll back the failed tuning transaction"
			return 1
		}
		SYSCTL_NEW=''
		log "removed managed keys from $SYSCTL_CONF (backup kept alongside it)"
	elif [ "$invalidate_stale" = 1 ] && [ "$HAD_BACKUP" = 1 ]; then
		rm -f "$BACKUP" || {
			fail "cannot discard the stale $SYSCTL_CONF backup"
			rollback_enable || fail "cannot roll back the failed tuning transaction"
			return 1
		}
		BACKUP_CHANGED=1
	fi

	DROPIN_CHANGED=0
	BACKUP_CHANGED=0
	return 0
}

rollback_disable() {
	local failed=0
	if [ "$DROPIN_CHANGED" = 1 ]; then
		if restore_snapshot "$DROPIN" "$DROPIN_OLD" "$HAD_DROPIN"; then
			DROPIN_OLD=''
		else
			failed=1
		fi
	fi
	if [ "$SYSCTL_CHANGED" = 1 ]; then
		if restore_snapshot "$SYSCTL_CONF" "$SYSCTL_OLD" 1; then
			SYSCTL_OLD=''
		else
			failed=1
		fi
	fi
	[ "$failed" = 0 ]
}

disable_persistent() {
	HAD_DROPIN=0
	HAD_BACKUP=0
	DROPIN_CHANGED=0
	SYSCTL_CHANGED=0
	RESTORE_NEEDED=0

	[ ! -L "$DROPIN" ] || {
		fail "$DROPIN is a symlink; refusing to remove it"
		return 1
	}
	[ ! -L "$BACKUP" ] || {
		fail "$BACKUP is a symlink; refusing to use or remove it"
		return 1
	}
	[ ! -e "$DROPIN" ] && [ ! -L "$DROPIN" ] || HAD_DROPIN=1
	[ ! -e "$BACKUP" ] && [ ! -L "$BACKUP" ] || HAD_BACKUP=1

	# 只有活跃 drop-in 才赋予备份“待恢复”含义。没有 drop-in 的旧备份只需
	# 丢弃，不能把旧值重新注入 sysctl.conf。
	if [ "$HAD_DROPIN" = 1 ]; then
		stage_restored_sysctl_conf || return 1
	fi

	if [ "$RESTORE_NEEDED" = 1 ]; then
		SYSCTL_OLD="$(snapshot_file "$SYSCTL_CONF")" || return 1
	fi
	if [ "$HAD_DROPIN" = 1 ]; then
		DROPIN_OLD="$(snapshot_file "$DROPIN")" || return 1
	fi

	if [ "$RESTORE_NEEDED" = 1 ]; then
		mv -f "$SYSCTL_NEW" "$SYSCTL_CONF" || {
			fail "cannot atomically restore $SYSCTL_CONF"
			return 1
		}
		SYSCTL_NEW=''
		SYSCTL_CHANGED=1
	fi

	if [ "$HAD_DROPIN" = 1 ]; then
		rm -f "$DROPIN" || {
			fail "cannot remove $DROPIN"
			rollback_disable || fail "cannot roll back the failed tuning transaction"
			return 1
		}
		DROPIN_CHANGED=1
	fi

	if [ "$HAD_BACKUP" = 1 ]; then
		rm -f "$BACKUP" || {
			fail "cannot retire the $SYSCTL_CONF backup"
			rollback_disable || fail "cannot roll back the failed tuning transaction"
			return 1
		}
	fi

	SYSCTL_CHANGED=0
	DROPIN_CHANGED=0
	[ "$RESTORE_NEEDED" = 0 ] || log "restored the previously managed keys to $SYSCTL_CONF"
	[ "$HAD_DROPIN" = 0 ] || log "removed $DROPIN"
	return 0
}

# sysctl -w 失败不中止: 缺 kmod-sched-cake 时只有 qdisc 那一行设不上,
# 其余三项照样应该生效。失败的键收集起来一并报告。
apply_key() {
	local key="$1" value="$2"
	if $SYSCTL_BIN -w "$key=$value" >/dev/null 2>&1; then
		return 0
	fi
	FAILED="${FAILED}${FAILED:+ }${key}"
	return 1
}

apply_irqbalance() {
	local wanted="$1"

	# irqbalance 是独立软件包, 没装就跳过而不是报错。
	[ -x "$INIT_DIR/irqbalance" ] || return 0

	$UCI_BIN -q set "irqbalance.irqbalance=irqbalance" 2>/dev/null
	$UCI_BIN -q set "irqbalance.irqbalance.enabled=$wanted" || return 1
	$UCI_BIN -q commit irqbalance || return 1

	# 这些失败原先被 "|| true" 全部吞掉, 于是 UCI 和界面都显示已应用, 而
	# irqbalance 实际没起来。把失败收进 FAILED, 和内核参数用同一条报告路径。
	if [ "$wanted" = 1 ]; then
		"$INIT_DIR/irqbalance" enable >/dev/null 2>&1 || \
			FAILED="${FAILED}${FAILED:+ }irqbalance-enable"
		"$INIT_DIR/irqbalance" restart >/dev/null 2>&1 || \
			FAILED="${FAILED}${FAILED:+ }irqbalance-restart"
	else
		"$INIT_DIR/irqbalance" stop >/dev/null 2>&1 || \
			FAILED="${FAILED}${FAILED:+ }irqbalance-stop"
		"$INIT_DIR/irqbalance" disable >/dev/null 2>&1 || \
			FAILED="${FAILED}${FAILED:+ }irqbalance-disable"
	fi
	return 0
}

main() {
	local enabled irqbalance

	enabled="$(uci_get enabled)"
	[ -n "$enabled" ] || enabled=0

	irqbalance="$(uci_get irqbalance)"
	[ -n "$irqbalance" ] || irqbalance=0
	case "$irqbalance" in 0|1) ;; *) irqbalance=0 ;; esac

	if [ "$enabled" != 1 ]; then
		# 关闭时只撤掉持久化, 不强行把运行时值改回去: 那些值可能是别的
		# 组件设的, 冒然回滚比留着更危险。
		disable_persistent || return 1
		apply_irqbalance "$irqbalance" || return 1
		if [ -n "$FAILED" ]; then
			log "these steps could not be applied: $FAILED"
			printf 'partial %s\n' "$FAILED"
			return 2
		fi
		printf 'disabled\n'
		return 0
	fi

	tcp_fastopen="$(uci_get tcp_fastopen)"
	default_qdisc="$(uci_get default_qdisc)"
	congestion_control="$(uci_get congestion_control)"
	backlog="$(uci_get tcp_max_syn_backlog)"

	valid_uint "$tcp_fastopen" || { fail "invalid tcp_fastopen"; return 1; }
	[ "$tcp_fastopen" -le 3 ] || { fail "tcp_fastopen must be 0-3"; return 1; }
	case "$default_qdisc" in
		cake|fq_codel) ;;
		cake_mq)
			supports_cake_mq || {
				fail "cake_mq requires OpenWrt 25.12 or newer"
				return 1
			}
			;;
		*) fail "invalid default_qdisc: $default_qdisc"; return 1 ;;
	esac
	case "$congestion_control" in
		bbr|cubic|reno) ;;
		*) fail "invalid congestion_control: $congestion_control"; return 1 ;;
	esac
	case "$backlog" in
		128|512|1024|2048) ;;
		*) fail "invalid tcp_max_syn_backlog: $backlog"; return 1 ;;
	esac

	stage_dropin || return 1
	stage_stripped_sysctl_conf || return 1
	commit_enable || return 1

	apply_key net.ipv4.tcp_fastopen "$tcp_fastopen"
	apply_key net.core.default_qdisc "$default_qdisc"
	apply_key net.ipv4.tcp_congestion_control "$congestion_control"
	apply_key net.ipv4.tcp_max_syn_backlog "$backlog"

	apply_irqbalance "$irqbalance" || return 1

	if [ -n "$FAILED" ]; then
		# 这些键写进了 drop-in 但当前内核设不上, 多半是缺对应模块。
		# 报出来而不是静默成功, 否则界面会显示一个并未生效的值。
		log "these keys could not be applied: $FAILED"
		printf 'partial %s\n' "$FAILED"
		return 2
	fi

	log "applied kernel tuning"
	printf 'ok\n'
	return 0
}

case "${1:-apply}" in
	restore)
		# 卸载时调用: 把托管键还回 sysctl.conf 并撤掉 drop-in, 否则用户原本的
		# 持久化设置在包被删掉之后就永远回不来了。
		disable_persistent || exit 1
		printf 'restored\n'
		exit 0
		;;
	apply) ;;
	*)
		fail "usage: $0 [apply|restore]"
		exit 2
		;;
esac

main
