include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for Singbox Subscribe Convert
PKG_RELEASE:=2
LUCI_DEPENDS:=+singbox-subscribe-convert +luci-base +rpcd +rpcd-mod-file
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
