#!/bin/sh
# Generate /etc/singbox-formula/config.yaml from UCI.

umask 077

FUNCTIONS_SH=${SBF_FUNCTIONS_SH:-/lib/functions.sh}
CONFIG=${SBF_CONFIG_NAME:-singbox_formula}
OUT=${SBF_CONFIG_OUT:-/etc/singbox-formula/config.yaml}
TMP=

die() {
	printf 'generate-config: %s\n' "$*" >&2
	exit 1
}

[ -r "$FUNCTIONS_SH" ] || die "cannot read $FUNCTIONS_SH"
. "$FUNCTIONS_SH" || die "cannot load $FUNCTIONS_SH"

cleanup() {
	[ -n "$TMP" ] && rm -f "$TMP"
}

trap cleanup 0
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

valid_scalar() {
	! printf '%s' "$1" | LC_ALL=C grep -q '[[:cntrl:]]'
}

yaml_quote() {
	if [ -z "$1" ]; then
		printf "''"
	else
		printf '%s' "$1" | sed "s/'/''/g; s/^/'/; s/$/'/"
	fi
}

bool_yaml() {
	case "$1" in
		1|true|yes|on|enabled) printf 'true' ;;
		*) printf 'false' ;;
	esac
}

uint_between() {
	local value="$1" minimum="$2" maximum="$3"
	case "$value" in
		''|*[!0-9]*) return 1 ;;
		0|[1-9]*) ;;
		*) return 1 ;;
	esac
	[ "${#value}" -le "${#maximum}" ] || return 1
	[ "$value" -ge "$minimum" ] 2>/dev/null || return 1
	[ "$value" -le "$maximum" ] 2>/dev/null
}

valid_http_url() {
	valid_scalar "$1" || return 1
	case "$1" in
		http://?*|https://?*) return 0 ;;
		*) return 1 ;;
	esac
}

valid_template_base_url() {
	local without_scheme authority host port
	valid_scalar "$1" || return 1
	case "$1" in
		http://127.0.0.1|http://127.0.0.1/*|http://localhost|http://localhost/*) return 0 ;;
		http://127.0.0.1:*|http://localhost:*) ;;
		*) return 1 ;;
	esac
	without_scheme=${1#http://}
	authority=${without_scheme%%/*}
	host=${authority%%:*}
	port=${authority#*:}
	case "$host" in 127.0.0.1|localhost) ;; *) return 1 ;; esac
	[ "$authority" = "$host:$port" ] || return 1
	uint_between "$port" 1 65535 || return 1
	case "$without_scheme" in "$authority"|"$authority"/*) return 0 ;; *) return 1 ;; esac
}

valid_output_path() {
	valid_scalar "$1" || return 1
	case "$1" in
		*//*|*/../*|*/./*|*/..|*/.) return 1 ;;
	esac
	case "$1" in
		/etc/momo/profiles/*.json|/etc/sing-box/*.json|/var/lib/singbox-formula/output/*.json) return 0 ;;
		*) return 1 ;;
	esac
}

valid_template_id() {
	case "$1" in
		''|*[!A-Za-z0-9_]*) return 1 ;;
		*) return 0 ;;
	esac
}

valid_template_file() {
	local stem
	valid_scalar "$1" || return 1
	case "$1" in
		''|*[!A-Za-z0-9._-]*) return 1 ;;
		*.json)
			stem=${1%.json}
			[ -n "$stem" ]
			return
			;;
		*) return 1 ;;
	esac
}

append_singbox_flag() {
	local url="$1" base fragment
	case "$url" in
		'') printf '%s' "$url"; return ;;
		*#*) base=${url%%#*}; fragment="#${url#*#}" ;;
		*) base=$url; fragment= ;;
	esac
	case "$base" in
		*\?flag=*|*'&'flag=*) ;;
		*\?*) base="${base}&flag=singbox" ;;
		*) base="${base}?flag=singbox" ;;
	esac
	printf '%s%s' "$base" "$fragment"
}

VALIDATION_ERROR=
DEFAULT_FOUND=0
DEFAULT_ENABLED=0
TEMPLATE_COUNT=0

validate_template() {
	local sid="$1" enabled name file no_node
	TEMPLATE_COUNT=$((TEMPLATE_COUNT + 1))
	valid_template_id "$sid" || {
		VALIDATION_ERROR="invalid template id: $sid"
		return 0
	}
	config_get_bool enabled "$sid" enabled 1
	config_get name "$sid" name "$sid"
	config_get file "$sid" file "$sid.json"
	config_get no_node "$sid" no_node '➜ Direct'
	valid_template_file "$file" || VALIDATION_ERROR="invalid template file for $sid"
	valid_scalar "$name" || VALIDATION_ERROR="invalid template name for $sid"
	valid_scalar "$no_node" || VALIDATION_ERROR="invalid no_node value for $sid"
	if [ "$sid" = "$default_template" ]; then
		DEFAULT_FOUND=1
		[ "$enabled" = 1 ] && DEFAULT_ENABLED=1
	fi
	return 0
}

emit_template() {
	local sid="$1" enabled name file no_node url url_yaml name_yaml no_node_yaml enabled_yaml status
	config_get_bool enabled "$sid" enabled 1
	config_get name "$sid" name "$sid"
	config_get file "$sid" file "$sid.json"
	config_get no_node "$sid" no_node '➜ Direct'
	url="${template_base_url%/}/$file"
	url_yaml=$(yaml_quote "$url") || {
		EMIT_ERROR="failed to quote template URL for $sid"
		return 1
	}
	name_yaml=$(yaml_quote "$name") || {
		EMIT_ERROR="failed to quote template name for $sid"
		return 1
	}
	no_node_yaml=$(yaml_quote "$no_node") || {
		EMIT_ERROR="failed to quote template no_node for $sid"
		return 1
	}
	enabled_yaml=$(bool_yaml "$enabled") || {
		EMIT_ERROR="failed to format template enabled value for $sid"
		return 1
	}
	cat <<EOF
  $sid:
    url: $url_yaml
    name: $name_yaml
    no_node: $no_node_yaml
    enabled: $enabled_yaml
EOF
	status=$?
	[ "$status" -eq 0 ] || EMIT_ERROR="failed to emit template $sid"
	return "$status"
}

emit_config() {
	cat <<EOF || return 1
# Generated by /usr/share/singbox-formula/generate-config.sh
server:
  port: $port
  read_timeout: 15
  write_timeout: $write_timeout
  idle_timeout: 60

auth:
  password: $password_yaml

subscription:
  url: $sub_url_yaml
  timeout: $sub_timeout
  refresh_interval: $refresh_interval

templates:
EOF
	EMIT_ERROR=
	config_foreach emit_template template || return 1
	[ -z "$EMIT_ERROR" ] || return 1
	cat <<EOF || return 1

default_template: $default_template_yaml

cache:
  directory: $cache_dir_yaml
  node_file: 'node.json'
  template_file: 'template.json'

cloudflare:
  enabled: false
  purge_url: ''
  api_token: ''
  api_key: ''
  api_email: ''

logging:
  production: true
  file: $log_file_yaml
  level: 'info'
  max_size: 10
  max_backups: 3
  max_age: 7
EOF
}

config_load "$CONFIG" || die "failed to load UCI config $CONFIG"

config_get_bool enabled main enabled 0
config_get boot_delay main boot_delay '90'
config_get port main port '9716'
config_get password main password '890716'
config_get sub_url main subscription_url ''
config_get sub_timeout main subscription_timeout '60'
config_get refresh_interval main refresh_interval '360'
config_get_bool singbox_flag main singbox_flag 1
config_get default_template main default_template 'momo_template'
config_get cache_dir main cache_dir '/var/lib/singbox-formula/cache'
config_get log_file main log_file '/var/log/singbox-formula/server.log'
config_get output_config main output_config '/etc/momo/profiles/config.json'
config_get template_base_url main template_base_url 'http://127.0.0.1/singbox-formula/templates'

uint_between "$port" 1 65535 || die "port must be an integer from 1 to 65535"
uint_between "$sub_timeout" 5 600 || die "subscription_timeout must be an integer from 5 to 600"
uint_between "$refresh_interval" 1 10080 || die "refresh_interval must be an integer from 1 to 10080"
uint_between "$boot_delay" 0 600 || die "boot_delay must be an integer from 0 to 600"

[ -n "$password" ] || die "password must not be empty"
valid_scalar "$password" || die "password contains a control character"
valid_scalar "$default_template" || die "default_template contains a control character"
valid_template_id "$default_template" || die "default_template is not canonical"
valid_scalar "$cache_dir" || die "cache_dir contains a control character"
valid_scalar "$log_file" || die "log_file contains a control character"
case "$cache_dir" in /*) ;; *) die "cache_dir must be absolute" ;; esac
case "$log_file" in /*) ;; *) die "log_file must be absolute" ;; esac
valid_template_base_url "$template_base_url" || die "template_base_url must use local HTTP loopback"
valid_output_path "$output_config" || die "output_config is outside the permitted JSON directories"

if [ -n "$sub_url" ]; then
	valid_http_url "$sub_url" || die "subscription_url must use HTTP or HTTPS"
elif [ "$enabled" = 1 ]; then
	die "subscription_url is required while the service is enabled"
fi

config_foreach validate_template template || die "failed to inspect templates"
[ -z "$VALIDATION_ERROR" ] || die "$VALIDATION_ERROR"
[ "$TEMPLATE_COUNT" -gt 0 ] || die "at least one template is required"
[ "$DEFAULT_FOUND" = 1 ] || die "default_template does not exist"
[ "$DEFAULT_ENABLED" = 1 ] || die "default_template is disabled"

[ "$singbox_flag" = 1 ] && sub_url=$(append_singbox_flag "$sub_url")
write_timeout=$((sub_timeout + 60))
password_yaml=$(yaml_quote "$password") || die "failed to quote password"
sub_url_yaml=$(yaml_quote "$sub_url") || die "failed to quote subscription URL"
default_template_yaml=$(yaml_quote "$default_template") || die "failed to quote default template"
cache_dir_yaml=$(yaml_quote "$cache_dir") || die "failed to quote cache directory"
log_file_yaml=$(yaml_quote "$log_file") || die "failed to quote log file"

OUT_DIR=$(dirname "$OUT") || die "cannot determine config directory"
OUT_BASE=${OUT##*/}
mkdir -p "$OUT_DIR" "$cache_dir" "$(dirname "$log_file")" || die "cannot create runtime directories"
TMP=$(mktemp "$OUT_DIR/.${OUT_BASE}.XXXXXX") || die "cannot create config staging file"

emit_config > "$TMP" || die "failed to write complete config staging file${EMIT_ERROR:+: $EMIT_ERROR}"

chmod 0600 "$TMP" || die "failed to secure config staging file"
if [ -f "$OUT" ]; then
	cmp -s "$TMP" "$OUT"
	cmp_status=$?
	case "$cmp_status" in
		0)
			rm -f "$TMP" || die "failed to remove unchanged staging file"
			TMP=
			chmod 0600 "$OUT" || die "failed to secure existing config"
			;;
		1)
			mv "$TMP" "$OUT" || die "failed to atomically replace config"
			TMP=
			;;
		*) die "failed to compare config staging file with existing config" ;;
	esac
else
	mv "$TMP" "$OUT" || die "failed to atomically replace config"
	TMP=
fi

printf '%s\n' "$OUT"
