#!/bin/sh
# Generate /etc/singbox-formula/config.yaml from UCI.

. /lib/functions.sh

CONFIG='singbox_formula'
OUT='/etc/singbox-formula/config.yaml'

_yaml_quote() {
	# single-quote scalar for YAML; escape single quotes by doubling them
	printf "%s" "$1" | sed "s/'/''/g; s/^/'/; s/$/'/"
}

_bool() {
	case "$1" in
		1|true|yes|on|enabled) printf 'true' ;;
		*) printf 'false' ;;
	esac
}

# Append flag=singbox to a subscription URL so providers that would otherwise
# return a base64 / URI node list hand back sing-box JSON instead. Leaves the URL
# untouched if empty or if it already carries a flag= query parameter, and joins
# with ? or & correctly depending on whether a query string is already present.
_append_singbox_flag() {
	local u="$1"
	case "$u" in
		'') printf '%s' "$u" ;;
		*\?flag=*|*'&'flag=*) printf '%s' "$u" ;;
		*\?*) printf '%s&flag=singbox' "$u" ;;
		*) printf '%s?flag=singbox' "$u" ;;
	esac
}

_emit_template() {
	local sid="$1"
	local enabled name file no_node base_url url
	config_get_bool enabled "$sid" enabled 1
	config_get name "$sid" name "$sid"
	config_get file "$sid" file "$sid.json"
	config_get no_node "$sid" no_node '➜ Direct'
	config_get base_url main template_base_url 'http://127.0.0.1/singbox-formula/templates'
	url="${base_url%/}/$file"
	cat <<EOF
  $sid:
    url: $(_yaml_quote "$url")
    name: $(_yaml_quote "$name")
    no_node: $(_yaml_quote "$no_node")
    enabled: $(_bool "$enabled")
EOF
}

mkdir -p /etc/singbox-formula /var/lib/singbox-formula/cache /var/log/singbox-formula /www/singbox-formula/templates

config_load "$CONFIG"

config_get port main port '9716'
config_get password main password '890716'
config_get sub_url main subscription_url ''
config_get sub_timeout main subscription_timeout '60'
config_get refresh_interval main refresh_interval '360'
config_get_bool singbox_flag main singbox_flag 1
[ "$singbox_flag" = "1" ] && sub_url="$(_append_singbox_flag "$sub_url")"
config_get default_template main default_template 'momo_template'
config_get cache_dir main cache_dir '/var/lib/singbox-formula/cache'
config_get log_file main log_file '/var/log/singbox-formula/server.log'

TMP="$OUT.$$"
{
cat <<EOF
# Generated by /usr/share/singbox-formula/generate-config.sh
server:
  port: $port
  read_timeout: 15
  write_timeout: 15
  idle_timeout: 60

auth:
  password: $(_yaml_quote "$password")

subscription:
  url: $(_yaml_quote "$sub_url")
  timeout: $sub_timeout
  refresh_interval: $refresh_interval

templates:
EOF
config_foreach _emit_template template
cat <<EOF

default_template: $(_yaml_quote "$default_template")

cache:
  directory: $(_yaml_quote "$cache_dir")
  node_file: 'node.json'
  template_file: 'template.json'

cloudflare:
  enabled: false
  purge_url: ''
  api_token: ''
  api_key: ''
  api_email: ''

logging:
  production: true
  file: $(_yaml_quote "$log_file")
  level: 'info'
  max_size: 10
  max_backups: 3
  max_age: 7
EOF
} > "$TMP" || exit 1
chmod 600 "$TMP"
mv "$TMP" "$OUT"
printf '%s\n' "$OUT"
